#!/bin/bash

if [[ $EUID -ne 0 ]]; then
    echo "This script must be run with sudo or as root"
    exit 1
fi

echo "INSTALLING..."

echo "Making Pictures Folder"
echo ""
mkdir Pictures
chown $USER Pictures

STARTUPDIR="/etc/init.d/"
STARTUP="/etc/init.d/camera_autostart"

if [ ! -d $STARTUPDIR ]; then
    echo "Making startup directory \"init.d\" in /etc"
    echo ""
    mkdir $STARTUPDIR
fi

if [ ! -f $STARTUP ]; then
    echo "Making startup script in /etc/init.d"
    echo ""

    #Adding the lines to the startup script
    touch $STARTUP
    echo "#!/bin/sh" >> $STARTUP
    echo "### BEGIN INIT INFO" >> $STARTUP
    echo "# Provides: SecurityCam" >> $STARTUP
    echo "# Required-Start: \$local_fs \$network" >> $STARTUP
    echo "# Required-Stop: \$local_fs" >> $STARTUP
    echo "# Default-Start: 2 3 4 5" >> $STARTUP
    echo "# Default-Stop: 0 1 6" >> $STARTUP
    echo "### END INIT INFO" >> $STARTUP
    echo "" >> $STARTUP
    echo "cd $PWD" >> $STARTUP
    echo "npm run start &>$PWD/server.log &" >> $STARTUP
    echo "cd /etc/init.d" >> $STARTUP
fi

exit 0

echo "installing npm and it's dependencies"
echo ""
curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -
apt-get -y install nodejs
npm i

echo "The default username is 'username'"
echo "The default password is 'password'"
echo "You can change this with the '/password' route,"
echo "Using the client application 'Change Password' functionality,"
echo "or by running a sha256 hash on a password of your choice then copying into 'config.js'"
echo "both exports.username and exports.password"
echo ""

rm install