#!/bin/sh
### BEGIN INIT INFO
# Provides: SecurityCam
# Required-Start: $local_fs $network
# Required-Stop: $local_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
### END INIT INFO

cd /home/pi/SecureCamServer
python /home/pi/SecureCamServer/autorun.py &
cd /etc/init.d
